{% set name = "pygeoutils" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7cc4872ddce725911e4fe9ebc88d8736a183b057bfaee995beea50e38853b29c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - cytoolz
    - geopandas-base >=1
    - pyogrio
    - netcdf4
    - numpy >=2
    - pyproj >=2.2
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - ujson
    - xarray >=2023.01.0

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pygeoutils
  summary: Utilities for manipulating geospatial, (Geo)JSON, and (Geo)TIFF data.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
